export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const START_FETCH_BOOKINGS_LIST = 'START_FETCH_BOOKINGS_LIST';
export const FETCH_BOOKINGS_LIST = 'FETCH_BOOKINGS_LIST';
export const FETCH_BOOKINGS_LIST_BY_DATE = 'FETCH_BOOKINGS_LIST_BY_DATE';
export const FETCH_LOCALLY_BOOKINGS_LIST = 'FETCH_LOCALLY_BOOKINGS_LIST';
export const SUCCESS_FETCH_BOOKINGS_LIST = 'SUCCESS_FETCH_BOOKINGS_LIST';
export const START_FETCH_LOCALLY_BOOKINGS_LIST = 'START_FETCH_LOCALLY_BOOKINGS_LIST';
export const SUCCESS_FETCH_LOCALLY_BOOKINGS_LIST = 'SUCCESS_FETCH_LOCALLY_BOOKINGS_LIST';
export const FAIL_FETCH_BOOKINGS_LIST = 'FAIL_FETCH_BOOKINGS_LIST';

export const INIT_UPDATE_BOOKING = 'INIT_UPDATE_BOOKING';
export const START_UPDATE_BOOKING = 'START_UPDATE_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const SUCCESS_UPDATE_BOOKING = 'SUCCESS_UPDATE_BOOKING';
export const RESET_UPDATE_BOOKING = 'RESET_UPDATE_BOOKING';
export const FAIL_UPDATE_BOOKING = 'FAIL_UPDATE_BOOKING';
export const RESET_SUCCESS_MESSAGE = 'RESET_SUCCESS_MESSAGE';
export const DISPLAY_NO_DATA_FOUND_MESSAGE = 'DISPLAY_NO_DATA_FOUND_MESSAGE';

export const START_CHANGE_TAB = 'START_CHANGE_TAB';
export const CHANGE_TAB = 'CHANGE_TAB';


export const START_FETCH_BOOKINGS_LIST_FOR_USER = 'START_FETCH_BOOKINGS_LIST_FOR_USER';
export const FETCH_BOOKINGS_LIST_FOR_USER = 'FETCH_BOOKINGS_LIST_FOR_USER';
export const FAIL_FETCH_BOOKINGS_LIST_FOR_USER = 'FAIL_FETCH_BOOKINGS_LIST_FOR_USER';
export const CHECK_TOTAL_PERSONS_NUMBER = 'CHECK_TOTAL_PERSONS_NUMBER';
export const SUCCESS_FETCH_BOOKINGS_LIST_FOR_USER = 'SUCCESS_FETCH_BOOKINGS_LIST_FOR_USER';
export const FETCH_BOOKINGS_LIST_FOR_USER_BY_DATE = 'FETCH_BOOKINGS_LIST_FOR_USER_BY_DATE';
export const UPDATE_TIMESLOTS = 'UPDATE_TIMESLOTS';
export const RESET_TIMESLOTS = 'RESET_TIMESLOTS';




export const GET_TODAY_DATE = 'GET_TODAY_DATE';
export const INPUT_CHANGED_HANDLER_FIRST_STEP = 'INPUT_CHANGED_HANDLER_FIRST_STEP';
export const INPUT_CHANGED_HANDLER_SECOND_STEP = 'INPUT_CHANGED_HANDLER_SECOND_STEP';
export const DISABLE_TIMESLOT = 'DISABLE_TIMESLOT';
export const ENABLE_TIMESLOT = 'ENABLE_TIMESLOT';
