export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const START_FETCH_BOOKINGS_LIST = 'START_FETCH_BOOKINGS_LIST';
export const FETCH_BOOKINGS_LIST = 'FETCH_BOOKINGS_LIST';
export const SUCCESS_FETCH_BOOKINGS_LIST = 'SUCCESS_FETCH_BOOKINGS_LIST';
export const FAIL_FETCH_BOOKINGS_LIST = 'FAIL_FETCH_BOOKINGS_LIST';

export const UPDATE_BOOKING = 'UPDATE_BOOKING';